import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({subsets: ['latin']})

export default function Home() {
  
  
  const fetchData = async () => {
    // get the data from the API
    const hops = fetch('/api/scrape')
      .then(response => response.json())
      .then(data => {
        console.log(data, "ca va topi")
      })
      .catch(error => {
        console.error('Errorsssss:', error);
      })
  }
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
        {/* Create table */}
        <table className={styles.table}>
          <thead>
          <tr>
            <th></th>
            <th>IDAHO</th>
            <th>MOSAIC</th>
            <th>CITRA</th>
          </tr>
          </thead>
          <tbody>
          <tr style={styles.red}>
            <th>Pinta</th>
            <td>150$</td>
            <td>Disponible</td>
            <td></td>
          </tr>
          <tr>
            <th>Beer appro</th>
            <td>
              <span className={styles.hopElement}>Lien</span>
              <span className={styles.hopElement}>150 $</span>
              <span className={styles.hopElement}>🟢</span>
            </td>
            <td>
              <span className={styles.hopElement}><a href="#">Lien</a></span>
              <span className={styles.hopElement}>150 $</span>
              <span className={styles.hopElement}>🔴</span>
            </td>
            <td>
              {/*  add fetch data button here */}
              <button onClick={fetchData}>Fetch data</button>
            </td>
          
          </tr>
          </tbody>
        </table>
      </main>
    </>
  )
}
