import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
        {/* Create table */}
        <table className={styles.table}>
          <thead>
          <tr>
            <th></th>
            <th>IDAHO</th>
            <th>MOSAIC</th>
            <th>CITRA</th>
          </tr>
          </thead>
          <tbody>
          <tr style={styles.red}>
            <th>Pinta</th>
            <td>150$</td>
            <td>Disponible</td>
            <td></td>
          </tr>
          <tr>
            <th>Beer appro</th>
            <td>
              <span className={styles.hopElement}>Lien</span>
              <span className={styles.hopElement}>150 $</span>
              <span className={styles.hopElement}>🟢</span>
            </td>
            <td>
              <span className={styles.hopElement}>Lien</span>
              <span className={styles.hopElement}>150 $</span>
              <span className={styles.hopElement}>🔴</span>
            </td>

          </tr>
          </tbody>
        </table>
  
        <table className={styles.styledTable}>
          <thead>
          <tr>
            <th></th>
            <th>ID</th>
            <th>NOM</th>
            <th>PRIX</th>
            <th>STOCK</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>001</td>
            <td>IPA</td>
            <td>5.99€</td>
            <td>En stock</td>
          </tr>
          <tr>
            <td>002</td>
            <td>Blonde</td>
            <td>4.99€</td>
            <td>En rupture de stock</td>
          </tr>
          <tr className={styles.highlighted}>
            <td>003</td>
            <td>Triple</td>
            <td>8.99€</td>
            <td>En stock</td>
          </tr>
          </tbody>
        </table>
      
      
      </main>
    </>
  )
}
